services:
    ContaoPageCookieBundle\EventListener\ProcessFormDataListener:
        tags:
            - { name: contao.hook, hook: processFormData, method: generateCookie, priority: 100 }

    ContaoPageCookieBundle\EventListener\InitializeSystemListener:
        tags:
            - { name: contao.hook, hook: initializeSystem, method: catchCookieToken, priority: 100 }

    ContaoPageCookieBundle\EventListener\GeneratePageListener:
        tags:
            - { name: contao.hook, hook: generatePage, method: __invoke, priority: 100 }

    ContaoPageCookieBundle\EventListener\SendNotificationMessageListener:
        tags:
            - { name: contao.hook, hook: sendNotificationMessage, method: addTokens, priority: 100 }